#!/usr/bin/env bash
# Render every inline Mermaid diagram in docs/*.md to SVG and open a gallery in
# the browser. Extension-free, works on any machine with npx (Node). GitHub renders
# these same diagrams automatically — this is just for local viewing.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="build/diagrams"
rm -rf "$OUT" && mkdir -p "$OUT"

html="$OUT/index.html"
echo "<!doctype html><meta charset=utf-8><title>Architecture diagrams</title>" > "$html"
echo "<style>body{font-family:sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem}img{max-width:100%;border:1px solid #ddd;border-radius:8px;padding:12px;background:#fff}h2{margin-top:2.5rem}</style>" >> "$html"
echo "<h1>Architecture diagrams</h1><p>Rendered from <code>docs/*.md</code>. Source of truth is the Mermaid in those files; this page is regenerated by <code>make diagrams</code>.</p>" >> "$html"

n=0
for md in docs/*.md; do
  # Split file into mermaid blocks; render each to its own SVG.
  awk '/```mermaid/{f=1;c++;next} /```/{if(f){f=0}} f{print > ("'"$OUT"'/blk_" c ".mmd")}' "$md"
  for mmd in "$OUT"/blk_*.mmd; do
    [ -e "$mmd" ] || continue
    n=$((n+1))
    svg="$OUT/diagram_$n.svg"
    npx -p @mermaid-js/mermaid-cli mmdc -i "$mmd" -o "$svg" >/dev/null 2>&1
    echo "<h2>$(basename "$md")</h2><img src='$(basename "$svg")'>" >> "$html"
    rm -f "$mmd"
  done
done

echo "Rendered $n diagram(s) -> $html"
open "$html" 2>/dev/null || echo "Open $html in your browser."
